name = __YOUR_PROJECT_NAME__
pages_build_output_dir = "dist"
compatibility_date = "2024-04-06"

[[ d1_databases ]]
binding = "DB"
migrations_dir= "./cloudflare/migrations"
database_name = __YOUR_DATABASE_NAME__
database_id = __YOUR_DATABASE_ID__

[[ env.production.d1_databases ]]
binding = "DB"
migrations_dir= "./cloudflare/migrations"
database_name = __YOUR_DATABASE_NAME__
database_id = __YOUR_DATABASE_ID__

[env.production.vars]
NUXT_PUBLIC_AUTH_BASE_URL=
NUXT_AUTH_ACCESS_TOKEN_JWT_SECRET =
NUXT_AUTH_REFRESH_TOKEN_JWT_SECRET =
NUXT_AUTH_EMAIL_FROM =
NUXT_AUTH_EMAIL_PROVIDER_API_KEY =
NUXT_AUTH_EMAIL_PROVIDER_NAME = "sendgrid"
NUXT_AUTH_OAUTH_GOOGLE_CLIENT_ID =
NUXT_AUTH_OAUTH_GOOGLE_CLIENT_SECRET =
NUXT_S3_ACCESS_KEY_ID =
NUXT_S3_BUCKET =
NUXT_S3_ENDPOINT =
NUXT_S3_SECRET_ACCESS_KEY =