name = "nuxt-cloudflare"
pages_build_output_dir = "dist"
compatibility_date = "2024-04-06"

[[ d1_databases ]]
binding = "DB"
database_name = "nuxt-cf-db"
database_id = "8f61b136-bef6-47f3-8c2f-010064ecc0d7"
migrations_dir= "./cloudflare/migrations"